config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  mount Shoppe::Engine => "/shoppe"
  resources :tournaments
  resources :posts
  resources :players do
    collection do
      post :import
      get :girls
      get :women
      get :juniors
      get :all
      
    end
  end

  get "players/", to: "players#index"
  get "products/", to: "products#index"
  get "product/:permalink", to: "products#show", as: "product"
  post "product/:permalink", to: "products#buy", as: "buy"

  get "basket", to: "orders#show"
  delete "basket", to: "orders#destroy"
  match "checkout", to: "orders#checkout", as: "checkout", via: [:get, :patch]
  match "checkout/pay", to: "orders#payment", as: "checkout_payment", via: [:get, :post]
  match "checkout/confirm", to: "orders#confirmation", as: "checkout_confirmation", via: [:get, :post]
    

  get '/', to: 'home#index'
  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@latest_posts = Post.order(created_at: :desc).limit(5).page params[:page]
		@latest_tourneys = Tournament.order(created_at: :desc).limit(5)
		@top_ten = Player.where("flag !='i'").order(rating: :desc).limit(10)
		@top_juniors = Player.where("birthday>=#{Date.today.strftime('%Y').to_i - 20}").order(rating: :desc).limit(10)
		@top_girls = Player.where("sex = 'F' AND rating > 0 AND birthday>=#{Date.today.strftime('%Y').to_i - 20}").order(rating: :desc).limit(10)
		@top_women = Player.where("sex = 'F' AND rating > 0").order(rating: :desc).limit(10)
	end
	
	
end

app/views/home/index.haml
.ui.container
  .ui.grid.container.segment
    #homesidebar.four.wide.column.ui.relaxed.divided.items.large.screen.only
      .ui.segment
        - @latest_tourneys.each do |tournament|
          .item
            .content
              %h4.ui.header
                = link_to tournament.name, tournament
              .meta
                %p
                  %b
                    Date: 
                  = tournament.date.strftime('%A, %B %d %Y')        
              .description
                %p
                  %b
                    Venue:
                  = tournament.venue        
              .extra
                - if Date.current < tournament.registration_deadline
                  %p
                    %b
                      Registration Ends On:
                    = tournament.registration_deadline.strftime('%B %d %Y, %l:%M')
                -else
                  %p.completed-tourney Registration Closed

                - if admin_signed_in?
                  .extra
                    = link_to 'Edit', edit_tournament_path(tournament)
                    = link_to 'Destroy', tournament, :method => :delete, :data => { :confirm => 'Are you sure?' }


    .ui.relaxed.divided.items.two.column.row.twelve.wide.computer.sixteen.wide.mobile.column
      - @latest_posts.each do |post|
        .item.row
          .ui.medium.image.bordered.column
            = image_tag post.image.url(:small), class:'postimage'
          .content.column
            .postcontent.ui.container
              .ui.segment.postexerpt
                %h4.ui.header
                  = link_to post.title, post
                = truncate(post.content, :length => 300, :omission => "" , :escape => false)+'...'
                .meta
                  %p Posted On:
                  = post.created_at.to_date.strftime('%B %d %Y')

                - if admin_signed_in?       
                  .extra
                    = link_to 'Edit ', edit_post_path(post)
                    = link_to 'Destroy', post, :method => :delete, :data => { :confirm => 'Are you sure?' }
      = paginate @latest_posts
      .ui.segment.bottom.attached
        %h4.ui.center.aligned.header
          = link_to 'View All Posts', posts_path    

  .ui.grid.container.segment.stackable
    .four.wide.column
      %h3.ui.header.topten Top Ten Overall
      %table.ui.celled.table.unstackable
        %thead
          %tr
            %th Name
            %th Rating
            -# %th Rapid
            -# %th Blitz

        %tbody
          - @top_ten.each do |player|
            %tr
              %td= link_to player.name, player
              %td= player.rating
              -# %td
              -#   - if player.rapid <= 0
              -#     = '-'
              -#   - else
              -#     = player.rapid
              -# %td
              -#   - if player.blitz <= 0
              -#     = '-'
              -#   - else
              -#     = player.blitz

    .ui.vertical.divider
    
    .four.wide.column
      %h3.ui.header.topten Top Juniors
      %table.ui.celled.table.unstackable
        %thead
          %tr
            %th Name
            %th Rating

        %tbody
          - @top_juniors.each do |player|
            %tr
              %td= link_to player.name, player
              %td= player.rating

    .ui.vertical.divider

    .four.wide.column
      %h3.ui.header.topten Top Girls
      %table.ui.celled.table.unstackable
        %thead
          %tr
            %th Name
            %th Rating

        %tbody
          - @top_girls.each do |player|
            %tr
              %td= link_to player.name, player
              %td= player.rating

    .ui.vertical.divider

    .four.wide.column
      %h3.ui.header.topten Top Women
      %table.ui.celled.table.unstackable
        %thead
          %tr
            %th Name
            %th Rating


        %tbody
          - @top_women.each do |player|
            %tr
              %td= link_to player.name, player
              %td= player.rating
    