config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  mount Shoppe::Engine => "/shoppe"
  resources :tournaments
  resources :posts
  resources :players do
    collection do
      post :import
      get :girls
      get :women
      get :juniors
      get :all
      
    end
  end

  get "players/", to: "players#index"
  get "products/", to: "products#index"
  get "product/:permalink", to: "products#show", as: "product"
  post "product/:permalink", to: "products#buy", as: "buy"

  get "basket", to: "orders#show"
  delete "basket", to: "orders#destroy"
  match "checkout", to: "orders#checkout", as: "checkout", via: [:get, :patch]
  match "checkout/pay", to: "orders#payment", as: "checkout_payment", via: [:get, :post]
  match "checkout/confirm", to: "orders#confirmation", as: "checkout_confirmation", via: [:get, :post]
    

  get '/', to: 'home#index'
  root 'home#index'

end

app/models/player.rb
class Player < ActiveRecord::Base
	has_many :tournaments, :through => :player_contacts
	require 'csv'

	def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|

      player_hash = row.to_hash
      player = Player.where(fideid: player_hash["fideid"])

      if player.count == 1
        player.first.update_attributes(player_hash)
      else
        Player.create!(player_hash)
      end # end if !product.nil?
    	end # end CSV.foreach
  	end # end self.import(file)

  	def fideprofile
  		return "http://ratings.fide.com/card.phtml?event="+self.fideid.to_s
  	end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_filter :authenticate_admin!, :except =>[:show,:index,:girls,:women,:juniors,:all,:import,:search]
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    if params[:search]
      searchstring = params[:search].capitalize
      @players = Player.where("flag !='i' AND name LIKE ?","%#{searchstring}%").page params[:page]
    else
      @players = Player.where("flag !='i'").page params[:page]
    end
  end

  def import
    Player.import(params[:file])
    redirect_to root_url, notice: "Players Imported"
  end

  def girls
    if params[:search]
      searchstring = params[:search].capitalize
      @players = Player.where("sex = 'F' AND birthday>=#{Date.today.strftime('%Y').to_i - 20} AND name LIKE ?","%#{searchstring}%").page params[:page]
    else
      @players = Player.where("sex = 'F' AND birthday>=#{Date.today.strftime('%Y').to_i - 20}").page params[:page]
    end
  end

  def women
    if params[:search]
      searchstring = params[:search].capitalize
      @players = Player.where("sex = 'F' AND name LIKE ?","%#{searchstring}%").page params[:page]
    else
      @players = Player.where("sex = 'F'").page params[:page]
    end
  end

  def juniors
    if params[:search]
      searchstring = params[:search].capitalize
      @players = Player.where("birthday>=#{Date.today.strftime('%Y').to_i - 20} AND name LIKE ?","%#{searchstring}%").page params[:page]
    else
      @players = Player.where("birthday>=#{Date.today.strftime('%Y').to_i - 20}").page params[:page]
    end
  end  


  def all
    if params[:search]
      searchstring = params[:search].capitalize
      @players = Player.where("name LIKE ?","%#{searchstring}%").page params[:page]
    else
      @players = Player.all.page params[:page]
    end
  end


  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:fideid, :name, :rating, :k, :rapid, :blitz, :birthday)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.haml
= form_for @player do |f|
  - if @player.errors.any?
    #error_explanation
      %h2= "#{pluralize(@player.errors.count, "error")} prohibited this player from being saved:"
      %ul
        - @player.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :fideid
    = f.text_field :fideid
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :rating
    = f.number_field :rating
  .field
    = f.label :k
    = f.number_field :k
  .field
    = f.label :rapid
    = f.number_field :rapid
  .field
    = f.label :blitz
    = f.number_field :blitz
  .field
    = f.label :birthday
    = f.number_field :birthday
  .actions
    = f.submit 'Save'

app/views/players/all.haml
.ui.container
  .ui.center.aligned.header
    .ui.buttons.medium
      = link_to "Active Players", players_path, class:'ui button inactive-btn' 
      = link_to "Women", women_players_path, class:'ui button inactive-btn'
      = link_to "Juniors", juniors_players_path, class:'ui button inactive-btn'
      = link_to "Girls", girls_players_path, class:'ui button inactive-btn'
      = link_to "All Players", all_players_path, class:'ui blue button'

  .ui.tertiary.form.segment
    =form_tag all_players_path, class:'ui form', :method=>'get' do
      .field.ui.left.icon.input
        = text_field_tag :search, params[:search], placeholder: 'Search...'
        %button.ui.action.button.right.attached.playersearch       
          %i.search.icon

  .ui.container.ratingscontainer
    %table.ui.celled.table.unstackable
      %thead
        %tr
          %th FideID
          %th Name
          %th Title
          %th Rating
          %th K-Factor
          %th Rapid
          %th Blitz
          %th Birthday

      %tbody
        - @players.each do |player|
          %tr
            %td= player.fideid
            %td= link_to player.name, player
            %td= player.title
            %td= player.rating
            %td= player.k
            %td
              - if player.rapid <= 0
                = '-'
              - else
                = player.rapid
            %td
              - if player.blitz <= 0
                = '-'
              - else
                = player.blitz
            %td= player.birthday
    = paginate @players

app/views/players/edit.html.haml
.ui.container
  %h1 Editing player

  = render 'form'

  = link_to 'Show', @player
  \|
  = link_to 'Back', players_path

app/views/players/girls.haml
.ui.container
  .ui.center.aligned.header
    .ui.buttons.medium
      = link_to "Active Players", players_path, class:'ui button inactive-btn'
      = link_to "Women", women_players_path, class:'ui button inactive-btn'
      = link_to "Juniors", juniors_players_path, class:'ui button inactive-btn'
      = link_to "Girls", girls_players_path, class:'ui blue button'
      = link_to "All Players", all_players_path, class:'ui button inactive-btn'

  .ui.tertiary.form.segment
    =form_tag girls_players_path, class:'ui form', :method=>'get' do
      .field.ui.left.icon.input
        = text_field_tag :search, params[:search], placeholder: 'Search'
        %button.ui.action.button.right.attached.playersearch       
          %i.search.icon 

  .ui.container.ratingscontainer
    %table.ui.celled.table.unstackable
      %thead
        %tr
          %th FideID
          %th Name
          %th Title
          %th Rating
          %th K-Factor
          %th Rapid
          %th Blitz
          %th Birthday

      %tbody
        - @players.each do |player|
          %tr
            %td= player.fideid
            %td= link_to player.name, player
            %td= player.title
            %td= player.rating
            %td= player.k
            %td
              - if player.rapid <= 0
                = '-'
              - else
                = player.rapid
            %td
              - if player.blitz <= 0
                = '-'
              - else
                = player.blitz
            %td= player.birthday
    = paginate @players

app/views/players/index.html.haml
.ui.container
  -if flash[:notice]
    .ui.message
      %p= flash[:notice]

  .ui.center.aligned.header.quicklink-btns
    .ui.buttons.medium
      = link_to "Active Players", players_path, class:'blue ui button'
      = link_to "Women", women_players_path, class:'ui button inactive-btn'
      = link_to "Juniors", juniors_players_path, class:'ui button inactive-btn'
      = link_to "Girls", girls_players_path, class:'ui button inactive-btn'
      = link_to "All Players", all_players_path, class:'ui button inactive-btn'

  .ui.tertiary.form.segment
    =form_tag players_path, class:'ui form', :method=>'get' do
      .field.ui.left.icon.input
        = text_field_tag :search, params[:search], placeholder: 'Search...'
        %button.ui.action.button.right.attached.playersearch       
          %i.search.icon 

  .ui.container.ratingscontainer
    %table.ui.celled.table.unstackable
      %thead
        %tr
          %th FideID
          %th Name
          %th Title
          %th Rating
          %th K-Factor
          %th Rapid
          %th Blitz
          %th Birthday

      %tbody
        - @players.each do |player|
          %tr
            %td= player.fideid
            %td= link_to player.name, player
            %td= player.title
            %td= player.rating
            %td= player.k
            %td
              - if player.rapid <= 0
                = '-'
              - else
                = player.rapid
            %td
              - if player.blitz <= 0
                = '-'
              - else
                = player.blitz
            %td= player.birthday
    = paginate @players

  %br

  -if admin_signed_in?
    .ui.segment
      %h4 Import a CSV File
      = form_tag import_players_path, multipart: true do
        = file_field_tag :file
        = button_tag "Import CSV", type:'submit', class:'ui button'

app/views/players/juniors.haml
.ui.container
  .ui.center.aligned.header
    .ui.buttons.medium
      = link_to "Active Players", players_path, class:'ui button inactive-btn'
      = link_to "Women", women_players_path, class:'ui button inactive-btn'
      = link_to "Juniors", juniors_players_path, class:'ui blue button'
      = link_to "Girls", girls_players_path, class:'ui button inactive-btn'
      = link_to "All Players", all_players_path, class:'ui button inactive-btn'

  .ui.tertiary.form.segment
    =form_tag juniors_players_path, class:'ui form', :method=>'get' do
      .field.ui.icon.input
        = text_field_tag :search, params[:search], placeholder: 'Search...'
        %button.ui.action.button.right.attached.playersearch       
          %i.search.icon

  .ui.container.ratingscontainer
    %table.ui.celled.table.unstackable
      %thead
        %tr
          %th FideID
          %th Name
          %th Title
          %th Rating
          %th K-Factor
          %th Rapid
          %th Blitz
          %th Birthday

      %tbody
        - @players.each do |player|
          %tr
            %td= player.fideid
            %td= link_to player.name, player
            %td= player.title
            %td= player.rating
            %td= player.k
            %td
              - if player.rapid <= 0
                = '-'
              - else
                = player.rapid
            %td
              - if player.blitz <= 0
                = '-'
              - else
                = player.blitz
            %td= player.birthday
    = paginate @players

app/views/players/new.html.haml
.ui.container
  %h3 New player

  = render 'form'
  
  %i.angle.double.left.icon
  = link_to 'Back', players_path

app/views/players/show.html.haml
%p#notice= notice
.ui.container
  %iframe#fideprofile{:src => @player.fideprofile,:scrolling=>"no",:frameBorder=>"0"}

app/views/players/women.haml
.ui.container
  .ui.center.aligned.header
    .ui.buttons.medium
      = link_to "Active Players", players_path, class:'ui button inactive-btn'
      = link_to "Women", women_players_path, class:'ui blue button'
      = link_to "Juniors", juniors_players_path, class:'ui button inactive-btn'
      = link_to "Girls", girls_players_path, class:'ui button inactive-btn'
      = link_to "All Players", all_players_path, class:'ui button inactive-btn'

  .ui.tertiary.form.segment
    =form_tag women_players_path, class:'ui form', :method=>'get' do
      .field.ui.left.icon.input
        = text_field_tag :search, params[:search], placeholder: 'Search...'
        %button.ui.action.button.right.attached.playersearch       
          %i.search.icon
  .ui.container.ratingscontainer
    %table.ui.celled.table.unstackable
      %thead
        %tr
          %th FideID
          %th Name
          %th Title
          %th Rating
          %th K-Factor
          %th Rapid
          %th Blitz
          %th Birthday

      %tbody
        - @players.each do |player|
          %tr
            %td= player.fideid
            %td= link_to player.name, player
            %td= player.title
            %td= player.rating
            %td= player.k
            %td
              - if player.rapid <= 0
                = '-'
              - else
                = player.rapid
            %td
              - if player.blitz <= 0
                = '-'
              - else
                = player.blitz
            %td= player.birthday
    = paginate @players