config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  mount Shoppe::Engine => "/shoppe"
  resources :tournaments
  resources :posts
  resources :players do
    collection do
      post :import
      get :girls
      get :women
      get :juniors
      get :all
      
    end
  end

  get "players/", to: "players#index"
  get "products/", to: "products#index"
  get "product/:permalink", to: "products#show", as: "product"
  post "product/:permalink", to: "products#buy", as: "buy"

  get "basket", to: "orders#show"
  delete "basket", to: "orders#destroy"
  match "checkout", to: "orders#checkout", as: "checkout", via: [:get, :patch]
  match "checkout/pay", to: "orders#payment", as: "checkout_payment", via: [:get, :post]
  match "checkout/confirm", to: "orders#confirmation", as: "checkout_confirmation", via: [:get, :post]
    

  get '/', to: 'home#index'
  root 'home#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :image, presence: true
	validates_uniqueness_of :title

	has_attached_file :image, styles: { :small => "320x", :mini => "160x" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_admin!, :except =>[:show,:index]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
=begin
before_action :set_s3_direct_post, only: [:new, :edit, :create, :update]
=end


  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.page params[:page]
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :image, :content)
    end

=begin
    def set_s3_direct_post
     @s3_direct_post = S3_BUCKET.presigned_post(key: "${filename}", success_action_status: '201', acl: 'public-read')
    end
=end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= form_for(@post, html: { multipart: true, class: 'ui form'}) do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :image
    = f.file_field :image
  .field
    = f.label :content
    = f.cktext_area :content, :class => 'ckeditor'
  .actions
    = f.submit 'Save', class:'ui submit button'

app/views/posts/edit.html.haml
.ui.container.segment
  %h3.ui.header.centered Editing post

  = render 'form'

  = link_to 'Show', @post
  \|
  = link_to 'Back', posts_path

app/views/posts/index.html.haml
.ui.grid.container.segment.maincontent
  -if flash[:notice]
    .ui.message
      %p= flash[:notice]
  - if admin_signed_in?
    = link_to 'New Post', new_post_path, class:'ui green button'

  #postscontainer.ui.relaxed.divided.items.two.column.row
    - @posts.each do |post|
      .item.row
        .ui.medium.image.bordered.column
          = image_tag post.image.url(:small_image), class:'postimage'
        .content.column
          .postcontent.ui.container
            .ui.segment
              %h4.ui.header
                = link_to post.title, post
              = truncate(post.content, :length => 300, :omission => "" , :escape => false)+'...'
              .meta
                %p Posted On:
                = post.created_at.to_date.strftime('%B %d %Y')

              - if admin_signed_in?       
                .extra
                  = link_to 'Edit ', edit_post_path(post)
                  = link_to 'Destroy', post, :method => :delete, :data => { :confirm => 'Are you sure?' }
    = paginate @posts

app/views/posts/new.html.haml
.ui.container.segment
  %h3.ui.header.centered New Post
  = render 'form'

  = link_to 'Back', posts_path

app/views/posts/show.html.haml
.ui.container
  -if flash[:notice]
    .ui.message
      %i.info.circle.icon
      %p#notice= flash[:notice]

  .ui.contanier.segment
    %h3
      = @post.title
    .postcontent
      = @post.content.html_safe

  -if admin_signed_in?
    = link_to 'Edit', edit_post_path(@post)
    \|
    = link_to 'Back', posts_path
  -else
    %i.angle.double.left.icon
    = link_to 'Back', posts_path