config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  mount Shoppe::Engine => "/shoppe"
  resources :tournaments
  resources :posts
  resources :players do
    collection do
      post :import
      get :girls
      get :women
      get :juniors
      get :all
      
    end
  end

  get "players/", to: "players#index"
  get "products/", to: "products#index"
  get "product/:permalink", to: "products#show", as: "product"
  post "product/:permalink", to: "products#buy", as: "buy"

  get "basket", to: "orders#show"
  delete "basket", to: "orders#destroy"
  match "checkout", to: "orders#checkout", as: "checkout", via: [:get, :patch]
  match "checkout/pay", to: "orders#payment", as: "checkout_payment", via: [:get, :post]
  match "checkout/confirm", to: "orders#confirmation", as: "checkout_confirmation", via: [:get, :post]
    

  get '/', to: 'home#index'
  root 'home#index'

end

app/views/layouts/application.haml
!!!
%html
  %head
    %title Project Chess Zambia - Promoting Education Through Chess
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'ckeditor/ckeditor.js'
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico'
  %body
  #mainmenu.ui.sticky
    .ui.menu.grid.stackable
      .item.two.wide.column
        = link_to (image_tag 'logo1.jpg', class:'ui image'), root_path, id:'sitelogo'
      #sitename.item.six.wide.column
        %h2.ui.header.sitename Project Chess Zambia
      .item.eight.wide.column
        #navmenu.ui.green.inverted.menu.stackable
          = link_to "News", posts_path, class: "item"
          = link_to "Ratings", players_path, class: "item"
          = link_to "Tournaments", tournaments_path, class: "item"
          - if admin_signed_in?
            .right.menu
              .item
                %p Logged in as: 
                = current_admin.email
              .item
                = link_to " Change Password", edit_admin_password_path
              .item
                = link_to " Sign Out", destroy_admin_session_path,:method => :delete, :data => { :confirm => 'Are you sure?' }
          - else
            .right.menu
              .item
                %i.facebook.icon        
              .item
                %i.twitter.icon


  = yield